language: python
python:
    - 3.6
before_install:
    - sudo rm -f /etc/boto.cfg
install:
    - pip install boto3
    - pip install moto
    - pip install coverage
    - pip install pytest
    - pip install utils
branches:
    only:
        - master
        - develop
addons:
    sonarcloud:
        organization: "usdot-jpo-sdc-projects"
script:
    - coverage erase
    - sonar-scanner -X -D sonar.login=$SONAR_TOKEN
